name: Deploy Docker App 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      - name: Push Docker image
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Deploy to EC2 using SSM
        run: |
          aws ssm send-command \
            --instance-ids "${{ secrets.EC2_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --parameters commands='[
              "aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}",
              "docker pull ${{ secrets.ECR_REPOSITORY }}:latest",
              "docker stop docker-private-app || true",
              "docker rm docker-private-app || true",
              "docker run -d --name docker-private-app -p 5000:5000 ${{ secrets.ECR_REPOSITORY }}:latest"
            ]'